import type { Meal } from "./types";

export const meals: Meal[] = [
  // ---------------------------------------------------------------------------
  // SMOOTHIES
  // ---------------------------------------------------------------------------
  {
    id: "green-power-smoothie",
    name: "Green Power Smoothie",
    description:
      "Spinach, frozen banana, frozen mango, flax seeds, oat milk, protein powder.",
    servings: 1,
    ingredients: [
      { item: "spinach", amount: "2 big handfuls" },
      { item: "frozen banana", amount: "1" },
      { item: "frozen mango chunks", amount: "1/2 cup" },
      { item: "ground flax seeds", amount: "1 tbsp" },
      { item: "chia seeds", amount: "1 tbsp", note: "optional" },
      { item: "protein powder", amount: "1 scoop" },
      { item: "oat milk", amount: "1.5 cups" },
    ],
    steps: [
      "Add oat milk and spinach to blender first, blend until smooth.",
      "Add frozen banana, mango, flax, chia, and protein powder.",
      "Blend until smooth. Add more oat milk if too thick.",
    ],
    categories: ["smoothie"],
    prepMinutes: 5,
    batchFriendly: false,
    portable: true,
    onePot: true,
    notes: "Rotate greens (kale, spinach) to vary nutrients.",
  },
  {
    id: "berry-oat-smoothie",
    name: "Berry Oat Smoothie",
    description:
      "Frozen mixed berries, rolled oats, almond butter, oat milk, protein powder, spinach.",
    servings: 1,
    ingredients: [
      { item: "frozen mixed berries", amount: "1 cup" },
      { item: "rolled oats", amount: "1/3 cup" },
      { item: "almond butter", amount: "1 tbsp" },
      { item: "spinach", amount: "1 handful" },
      { item: "protein powder", amount: "1 scoop" },
      { item: "oat milk", amount: "1.5 cups" },
    ],
    steps: [
      "Add oat milk, spinach, and oats to blender. Blend until oats are broken down.",
      "Add berries, almond butter, and protein powder.",
      "Blend until smooth.",
    ],
    categories: ["smoothie"],
    prepMinutes: 5,
    batchFriendly: false,
    portable: true,
    onePot: true,
    notes:
      "Oats add soluble fiber (cholesterol benefit). Almond butter keeps it filling.",
  },
  {
    id: "tropical-anti-inflammatory",
    name: "Tropical Anti-Inflammatory",
    description:
      "Frozen pineapple, turmeric, ginger, coconut water, flax, spinach, protein powder.",
    servings: 1,
    ingredients: [
      { item: "frozen pineapple", amount: "1 cup" },
      { item: "fresh turmeric", amount: "1 inch piece", note: "or 1/2 tsp powder" },
      { item: "fresh ginger", amount: "1/2 inch piece" },
      { item: "black pepper", amount: "pinch", note: "activates curcumin" },
      { item: "ground flax seeds", amount: "1 tbsp" },
      { item: "spinach", amount: "1 handful" },
      { item: "protein powder", amount: "1 scoop" },
      { item: "coconut water", amount: "1.5 cups" },
    ],
    steps: [
      "Add coconut water, spinach, turmeric, and ginger to blender. Blend until smooth.",
      "Add pineapple, flax, protein powder, and black pepper.",
      "Blend until smooth.",
    ],
    categories: ["smoothie"],
    prepMinutes: 5,
    batchFriendly: false,
    portable: true,
    onePot: true,
    notes: "Fresh turmeric stains everything. Use powder if you don't want yellow fingers.",
  },

  // ---------------------------------------------------------------------------
  // INDIAN MAINS
  // ---------------------------------------------------------------------------
  {
    id: "red-lentil-dal",
    name: "Red Lentil Dal (Masoor Dal)",
    description:
      "Simple, fast dal. The workhorse meal — high in soluble fiber, pairs with rice or roti.",
    servings: 4,
    ingredients: [
      { item: "red lentils", amount: "1 cup", note: "rinsed until water runs clear" },
      { item: "water", amount: "3 cups" },
      { item: "onion", amount: "1 medium", note: "diced" },
      { item: "tomato", amount: "1 large", note: "diced, or 1/2 can diced tomatoes" },
      { item: "garlic", amount: "4 cloves", note: "minced" },
      { item: "ginger", amount: "1 inch piece", note: "grated" },
      { item: "turmeric", amount: "1/2 tsp" },
      { item: "cumin seeds", amount: "1 tsp" },
      { item: "ground coriander", amount: "1 tsp" },
      { item: "salt", amount: "1 tsp", note: "adjust to taste" },
      { item: "olive oil", amount: "2 tbsp" },
      { item: "lemon juice", amount: "1 tbsp" },
      { item: "cilantro", amount: "handful", note: "for topping" },
    ],
    steps: [
      "Rinse lentils in a strainer until water runs mostly clear.",
      "Heat olive oil in a pot over medium heat. Add cumin seeds and let them sizzle for 30 seconds.",
      "Add onion, cook until soft and lightly golden, about 5 minutes.",
      "Add garlic and ginger, cook 1 minute until fragrant.",
      "Add tomato, turmeric, and coriander. Stir and cook 2 minutes.",
      "Add lentils and water. Bring to a boil, then reduce to a simmer.",
      "Simmer uncovered 15-20 minutes, stirring occasionally, until lentils are completely broken down and creamy.",
      "Add salt and lemon juice. Adjust consistency with water if needed.",
      "Top with cilantro. Serve with brown rice or whole wheat roti.",
    ],
    categories: ["flexible"],
    prepMinutes: 15,
    batchFriendly: true,
    portable: true,
    onePot: true,
    notes:
      "Freezes well in portions. Doubles easily. Gets thicker as it sits — add water when reheating.",
  },
  {
    id: "chana-masala",
    name: "Chana Masala",
    description:
      "Chickpeas in a spiced tomato sauce. High protein, high fiber, deeply satisfying.",
    servings: 4,
    ingredients: [
      { item: "canned chickpeas", amount: "2 cans (15 oz each)", note: "drained and rinsed" },
      { item: "onion", amount: "1 large", note: "diced" },
      { item: "canned diced tomatoes", amount: "1 can (14 oz)" },
      { item: "garlic", amount: "4 cloves", note: "minced" },
      { item: "ginger", amount: "1 inch piece", note: "grated" },
      { item: "garam masala", amount: "1.5 tsp" },
      { item: "ground cumin", amount: "1 tsp" },
      { item: "ground coriander", amount: "1 tsp" },
      { item: "turmeric", amount: "1/2 tsp" },
      { item: "kashmiri chili powder", amount: "1/2 tsp", note: "or paprika + pinch cayenne" },
      { item: "salt", amount: "1 tsp" },
      { item: "olive oil", amount: "2 tbsp" },
      { item: "lemon juice", amount: "2 tbsp" },
      { item: "cilantro", amount: "handful", note: "chopped" },
    ],
    steps: [
      "Heat olive oil over medium heat. Add onion, cook until golden, about 7 minutes.",
      "Add garlic and ginger, cook 1 minute.",
      "Add cumin, coriander, turmeric, and chili powder. Stir for 30 seconds until fragrant.",
      "Add canned tomatoes. Cook 5 minutes, stirring, until the sauce thickens slightly.",
      "Add chickpeas and 1/2 cup water. Stir to combine.",
      "Simmer 15 minutes. Mash a few chickpeas against the side of the pot to thicken the sauce.",
      "Add garam masala, salt, and lemon juice. Stir and taste for seasoning.",
      "Top with cilantro. Serve over rice or with roti.",
    ],
    categories: ["flexible"],
    prepMinutes: 20,
    batchFriendly: true,
    portable: true,
    onePot: true,
    notes: "Using canned chickpeas makes this a 25-minute meal. Tastes even better the next day.",
  },
  {
    id: "chicken-rogan-josh",
    name: "Chicken Rogan Josh",
    description:
      "Rich, aromatic Kashmiri curry. Chicken instead of lamb to keep saturated fat low.",
    servings: 4,
    ingredients: [
      { item: "chicken thighs (skinless, boneless)", amount: "1.5 lbs", note: "cut into chunks" },
      { item: "low-fat yogurt", amount: "1/2 cup" },
      { item: "onion", amount: "2 medium", note: "thinly sliced" },
      { item: "canned diced tomatoes", amount: "1 can (14 oz)" },
      { item: "garlic", amount: "5 cloves", note: "minced" },
      { item: "ginger", amount: "1.5 inch piece", note: "grated" },
      { item: "kashmiri chili powder", amount: "2 tsp", note: "for color + mild heat" },
      { item: "ground cumin", amount: "1 tsp" },
      { item: "ground coriander", amount: "1 tsp" },
      { item: "garam masala", amount: "1 tsp" },
      { item: "cardamom pods", amount: "4", note: "lightly crushed" },
      { item: "cinnamon stick", amount: "1 small" },
      { item: "cloves", amount: "3" },
      { item: "bay leaf", amount: "1" },
      { item: "salt", amount: "1 tsp" },
      { item: "olive oil", amount: "2 tbsp" },
      { item: "cilantro", amount: "for topping" },
    ],
    steps: [
      "Marinate chicken in yogurt, 1 tsp chili powder, and a pinch of salt for at least 15 minutes (or overnight).",
      "Heat olive oil in a heavy pot over medium heat. Add cardamom, cinnamon, cloves, and bay leaf. Let them sizzle 30 seconds.",
      "Add sliced onions. Cook until deeply golden, 10-12 minutes. Don't rush this.",
      "Add garlic and ginger, cook 1 minute.",
      "Add remaining chili powder, cumin, and coriander. Stir 30 seconds.",
      "Add tomatoes. Cook 5 minutes until sauce thickens.",
      "Add marinated chicken with all the yogurt. Stir to coat.",
      "Add 1/2 cup water. Bring to a simmer, cover, and cook 20 minutes until chicken is cooked through.",
      "Uncover, stir in garam masala and salt. Simmer 5 more minutes to thicken the sauce.",
      "Remove whole spices if you want. Top with cilantro. Serve with rice.",
    ],
    categories: ["dinner"],
    prepMinutes: 30,
    batchFriendly: true,
    portable: true,
    onePot: true,
    notes:
      "The Kashmiri chili gives the signature red color without too much heat. Can use lamb occasionally as a treat — just know it's higher in saturated fat.",
  },
  {
    id: "palak-dal",
    name: "Palak Dal (Spinach Lentils)",
    description:
      "Lentils and spinach in one pot. Gets you legumes and greens in a single meal.",
    servings: 4,
    ingredients: [
      { item: "red lentils or moong dal", amount: "1 cup", note: "rinsed" },
      { item: "fresh spinach", amount: "4 cups packed", note: "or 1 block frozen" },
      { item: "water", amount: "3 cups" },
      { item: "onion", amount: "1 medium", note: "diced" },
      { item: "garlic", amount: "3 cloves", note: "minced" },
      { item: "ginger", amount: "1 inch piece", note: "grated" },
      { item: "turmeric", amount: "1/2 tsp" },
      { item: "ground cumin", amount: "1 tsp" },
      { item: "olive oil", amount: "2 tbsp" },
      { item: "mustard seeds", amount: "1 tsp", note: "for tadka" },
      { item: "dried red chili", amount: "1-2", note: "for tadka" },
      { item: "salt", amount: "1 tsp" },
      { item: "lemon juice", amount: "1 tbsp" },
    ],
    steps: [
      "Rinse lentils. Add to a pot with water and turmeric. Bring to a boil, then simmer 15 minutes until soft.",
      "While lentils cook, heat 1 tbsp olive oil in a pan. Cook onion until soft, add garlic and ginger, cook 1 minute.",
      "Add cumin, stir 30 seconds. Add spinach and cook until wilted (2 min fresh, 5 min frozen).",
      "Add the spinach-onion mixture to the cooked lentils. Stir to combine. Simmer 5 minutes.",
      "Make the tadka: heat remaining 1 tbsp olive oil in a small pan. Add mustard seeds — when they start popping, add dried chili. Cook 15 seconds.",
      "Pour the tadka over the dal. Add salt and lemon juice. Stir.",
      "Serve with rice or roti.",
    ],
    categories: ["flexible"],
    prepMinutes: 20,
    batchFriendly: true,
    portable: true,
    onePot: true,
    notes: "Very forgiving recipe. Frozen spinach works perfectly and is zero prep.",
  },
  {
    id: "rajma",
    name: "Rajma (Kidney Bean Curry)",
    description:
      "Thick, hearty kidney bean curry. Comfort food with massive fiber.",
    servings: 4,
    ingredients: [
      { item: "canned kidney beans", amount: "2 cans (15 oz each)", note: "drained and rinsed" },
      { item: "onion", amount: "1 large", note: "finely diced" },
      { item: "canned diced tomatoes", amount: "1 can (14 oz)" },
      { item: "garlic", amount: "4 cloves", note: "minced" },
      { item: "ginger", amount: "1 inch piece", note: "grated" },
      { item: "garam masala", amount: "1.5 tsp" },
      { item: "ground cumin", amount: "1 tsp" },
      { item: "ground coriander", amount: "1 tsp" },
      { item: "turmeric", amount: "1/2 tsp" },
      { item: "kashmiri chili powder", amount: "1/2 tsp" },
      { item: "salt", amount: "1 tsp" },
      { item: "olive oil", amount: "2 tbsp" },
      { item: "cilantro", amount: "for topping" },
    ],
    steps: [
      "Heat olive oil over medium heat. Add onion, cook until golden, about 7 minutes.",
      "Add garlic and ginger, cook 1 minute.",
      "Add cumin, coriander, turmeric, and chili powder. Stir 30 seconds.",
      "Add tomatoes. Cook 5 minutes until saucy.",
      "Add kidney beans and 1 cup water. Stir well.",
      "Bring to a simmer. Cook 20 minutes, mashing some beans against the side to thicken the gravy.",
      "Stir in garam masala and salt. Simmer 5 more minutes.",
      "Top with cilantro. Serve over rice.",
    ],
    categories: ["flexible"],
    prepMinutes: 20,
    batchFriendly: true,
    portable: true,
    onePot: true,
    notes: "Thickens a lot as it cools. Add water when reheating. Great for meal prep containers.",
  },
  {
    id: "tofu-tikka-masala",
    name: "Tofu Tikka Masala",
    description:
      "Crispy tofu in a rich tomato-cashew cream sauce. No dairy needed.",
    servings: 4,
    ingredients: [
      { item: "firm tofu", amount: "1 block (14 oz)", note: "pressed and cubed" },
      { item: "canned diced tomatoes", amount: "1 can (14 oz)" },
      { item: "raw cashews", amount: "1/4 cup", note: "soaked in hot water 15 min" },
      { item: "onion", amount: "1 large", note: "diced" },
      { item: "garlic", amount: "4 cloves", note: "minced" },
      { item: "ginger", amount: "1 inch piece", note: "grated" },
      { item: "garam masala", amount: "1.5 tsp" },
      { item: "ground cumin", amount: "1 tsp" },
      { item: "kashmiri chili powder", amount: "1 tsp" },
      { item: "turmeric", amount: "1/2 tsp" },
      { item: "dried fenugreek leaves", amount: "1 tsp", note: "optional but great" },
      { item: "salt", amount: "1 tsp" },
      { item: "olive oil", amount: "3 tbsp" },
      { item: "cilantro", amount: "for topping" },
    ],
    steps: [
      "Press tofu: wrap in a clean towel, put something heavy on top for 10 minutes.",
      "Soak cashews in hot water while you prep everything else.",
      "Cut tofu into cubes. Toss with 1 tbsp olive oil, 1/2 tsp cumin, pinch of salt and chili powder.",
      "Bake tofu at 400F on a lined sheet pan for 25 minutes, flipping halfway. Or pan-fry in a non-stick pan until golden.",
      "While tofu cooks, heat 2 tbsp olive oil. Cook onion until golden, 7 minutes.",
      "Add garlic and ginger, cook 1 minute. Add remaining spices, stir 30 seconds.",
      "Add canned tomatoes and 1/4 cup water. Simmer 10 minutes.",
      "Drain cashews. Blend cashews with 1/4 cup water until completely smooth.",
      "Add cashew cream to the sauce. Stir and simmer 5 minutes.",
      "Add tofu to the sauce. Stir gently. Add fenugreek leaves and salt.",
      "Serve over rice, topped with cilantro.",
    ],
    categories: ["dinner"],
    prepMinutes: 30,
    batchFriendly: true,
    portable: true,
    onePot: false,
    notes: "Cashew cream is the move — tastes rich without any saturated fat from cream. Sauce freezes well without the tofu.",
  },

  // ---------------------------------------------------------------------------
  // MEDITERRANEAN / BOWLS
  // ---------------------------------------------------------------------------
  {
    id: "grain-bowl",
    name: "Grain Bowl",
    description:
      "Modular lunch. Prep components once, assemble daily in 5 minutes.",
    servings: 1,
    ingredients: [
      { item: "cooked quinoa or brown rice", amount: "3/4 cup" },
      { item: "roasted vegetables", amount: "1 cup", note: "whatever you have" },
      { item: "canned chickpeas", amount: "1/2 can", note: "drained, rinsed" },
      { item: "greens", amount: "1 handful", note: "spinach, arugula, or kale" },
      { item: "tahini", amount: "1 tbsp" },
      { item: "lemon juice", amount: "1 tbsp" },
      { item: "olive oil", amount: "1 tsp" },
      { item: "salt and pepper", amount: "to taste" },
    ],
    steps: [
      "Put grain in container. Top with roasted veg and chickpeas.",
      "Add greens on the side (so they don't wilt if packing for later).",
      "Mix tahini, lemon juice, olive oil, and a splash of water into a dressing. Drizzle on top.",
    ],
    categories: ["lunch"],
    prepMinutes: 5,
    batchFriendly: true,
    portable: true,
    onePot: false,
    notes:
      "The key is batch-prepping the components: cook a big pot of grain, roast a sheet pan of veg. Then this is pure assembly all week.",
  },
  {
    id: "mediterranean-lentil-soup",
    name: "Lentil Soup (Mediterranean)",
    description:
      "Different vibe from Indian dal. Lemony, earthy, smoky. Freezes perfectly.",
    servings: 6,
    ingredients: [
      { item: "green or brown lentils", amount: "1.5 cups", note: "rinsed" },
      { item: "carrot", amount: "2 medium", note: "diced" },
      { item: "celery", amount: "2 stalks", note: "diced" },
      { item: "onion", amount: "1 large", note: "diced" },
      { item: "garlic", amount: "4 cloves", note: "minced" },
      { item: "canned diced tomatoes", amount: "1 can (14 oz)" },
      { item: "vegetable or chicken broth", amount: "4 cups" },
      { item: "water", amount: "2 cups" },
      { item: "ground cumin", amount: "1 tsp" },
      { item: "smoked paprika", amount: "1 tsp" },
      { item: "olive oil", amount: "2 tbsp" },
      { item: "lemon juice", amount: "2 tbsp" },
      { item: "salt", amount: "1 tsp" },
      { item: "black pepper", amount: "1/2 tsp" },
      { item: "baby spinach", amount: "2 cups", note: "optional, stir in at end" },
    ],
    steps: [
      "Heat olive oil in a large pot. Add onion, carrot, and celery. Cook 5-7 minutes until softened.",
      "Add garlic, cumin, and smoked paprika. Cook 1 minute.",
      "Add lentils, tomatoes, broth, and water. Bring to a boil.",
      "Reduce heat, simmer 25-30 minutes until lentils are tender.",
      "If using spinach, stir it in and let it wilt, about 2 minutes.",
      "Add lemon juice, salt, and pepper. Taste and adjust.",
      "Serve as-is or blend half for a creamier texture.",
    ],
    categories: ["flexible"],
    prepMinutes: 15,
    batchFriendly: true,
    portable: true,
    onePot: true,
    notes: "Makes a huge batch. Freezes perfectly in individual portions. Great thermos lunch.",
  },
  {
    id: "shakshuka",
    name: "Shakshuka",
    description:
      "Eggs poached in spiced tomato sauce. Quick, one-pan, satisfying.",
    servings: 2,
    ingredients: [
      { item: "eggs", amount: "4" },
      { item: "canned diced tomatoes", amount: "1 can (14 oz)" },
      { item: "onion", amount: "1 medium", note: "diced" },
      { item: "bell pepper", amount: "1", note: "diced" },
      { item: "garlic", amount: "3 cloves", note: "minced" },
      { item: "ground cumin", amount: "1 tsp" },
      { item: "smoked paprika", amount: "1 tsp" },
      { item: "chili flakes", amount: "1/4 tsp", note: "or more to taste" },
      { item: "olive oil", amount: "1 tbsp" },
      { item: "salt", amount: "1/2 tsp" },
      { item: "cilantro or parsley", amount: "for topping" },
    ],
    steps: [
      "Heat olive oil in a skillet over medium heat. Add onion and bell pepper, cook 5 minutes.",
      "Add garlic, cumin, paprika, and chili flakes. Cook 1 minute.",
      "Add tomatoes and salt. Simmer 10 minutes until the sauce thickens.",
      "Make 4 wells in the sauce with a spoon. Crack an egg into each well.",
      "Cover the pan. Cook 5-7 minutes until egg whites are set but yolks are still runny.",
      "Top with herbs. Eat with crusty bread or roti.",
    ],
    categories: ["breakfast", "dinner"],
    prepMinutes: 20,
    batchFriendly: false,
    portable: false,
    onePot: true,
    notes: "You can make the sauce ahead and just poach eggs in it when you're ready to eat.",
  },
  {
    id: "hummus-wrap",
    name: "Hummus Wrap",
    description:
      "The ultimate no-cook portable lunch. 5 minutes if ingredients are stocked.",
    servings: 1,
    ingredients: [
      { item: "whole wheat wrap", amount: "1 large" },
      { item: "hummus", amount: "3 tbsp", note: "thick layer" },
      { item: "cucumber", amount: "1/3", note: "sliced thin" },
      { item: "tomato", amount: "1/2", note: "sliced" },
      { item: "greens", amount: "handful", note: "spinach or arugula" },
      { item: "pickled onion", amount: "2 tbsp", note: "optional but great" },
      { item: "feta", amount: "small crumble", note: "optional, small amount" },
    ],
    steps: [
      "Spread hummus across the entire wrap.",
      "Layer cucumber, tomato, greens, pickled onion.",
      "Roll tightly, tucking in the sides.",
      "Cut in half. Wrap in foil for transport.",
    ],
    categories: ["lunch"],
    prepMinutes: 5,
    batchFriendly: false,
    portable: true,
    onePot: true,
    notes: "Keep hummus, wraps, and some veg stocked and this is always an option. Zero cooking.",
  },

  // ---------------------------------------------------------------------------
  // FISH
  // ---------------------------------------------------------------------------
  {
    id: "baked-salmon-sheet-pan",
    name: "Baked Salmon with Roasted Veg",
    description:
      "Everything on one sheet pan. Omega-3s that directly improve lipid profiles.",
    servings: 2,
    ingredients: [
      { item: "salmon fillets", amount: "2 (6 oz each)" },
      { item: "broccoli", amount: "2 cups florets" },
      { item: "sweet potato", amount: "1 medium", note: "cubed small" },
      { item: "olive oil", amount: "2 tbsp" },
      { item: "garlic", amount: "2 cloves", note: "minced" },
      { item: "lemon", amount: "1", note: "half for juice, half for slices" },
      { item: "salt", amount: "3/4 tsp" },
      { item: "black pepper", amount: "1/2 tsp" },
      { item: "smoked paprika", amount: "1/2 tsp", note: "optional" },
    ],
    steps: [
      "Preheat oven to 425F. Line a sheet pan with parchment.",
      "Toss sweet potato with 1 tbsp olive oil, salt, pepper. Spread on pan. Roast 10 minutes.",
      "Toss broccoli with remaining olive oil. Add to the pan around the sweet potato.",
      "Place salmon on the pan. Rub with garlic, squeeze lemon juice over, add lemon slices on top. Season with salt, pepper, paprika.",
      "Roast 12-15 minutes until salmon flakes easily.",
      "One pan, done.",
    ],
    categories: ["dinner"],
    prepMinutes: 10,
    batchFriendly: false,
    portable: true,
    onePot: true,
    notes:
      "Sweet potato goes in first because it takes longer. Salmon leftovers are great cold on a grain bowl the next day.",
  },
  {
    id: "goan-fish-curry",
    name: "Fish Curry (Goan Style)",
    description:
      "Tangy coconut fish curry. Light coconut milk keeps it reasonable on saturated fat.",
    servings: 4,
    ingredients: [
      { item: "white fish fillets", amount: "1 lb", note: "cod, tilapia, or similar — cut into chunks" },
      { item: "light coconut milk", amount: "1 can (13.5 oz)" },
      { item: "tomato", amount: "1 large", note: "diced" },
      { item: "onion", amount: "1 medium", note: "diced" },
      { item: "garlic", amount: "3 cloves", note: "minced" },
      { item: "ginger", amount: "1 inch piece", note: "grated" },
      { item: "turmeric", amount: "1/2 tsp" },
      { item: "kashmiri chili powder", amount: "1 tsp" },
      { item: "ground coriander", amount: "1 tsp" },
      { item: "tamarind paste", amount: "1 tbsp", note: "or 2 tbsp lemon juice" },
      { item: "salt", amount: "3/4 tsp" },
      { item: "olive oil", amount: "1 tbsp" },
      { item: "cilantro", amount: "for topping" },
    ],
    steps: [
      "Heat olive oil. Cook onion until soft, 5 minutes.",
      "Add garlic and ginger, cook 1 minute.",
      "Add turmeric, chili powder, and coriander. Stir 30 seconds.",
      "Add tomato, cook 3 minutes until soft.",
      "Add coconut milk and tamarind paste. Stir and bring to a gentle simmer.",
      "Add fish pieces. Don't stir too much — let them cook gently in the sauce, 8-10 minutes.",
      "Add salt, taste and adjust. Top with cilantro.",
      "Serve over rice.",
    ],
    categories: ["dinner"],
    prepMinutes: 25,
    batchFriendly: true,
    portable: true,
    onePot: true,
    notes: "Light coconut milk is key. If you can find tamarind paste, it makes this dish — lemon juice works as a substitute.",
  },
  {
    id: "fish-grain-bowl",
    name: "Tuna/Salmon Grain Bowl",
    description:
      "Quick assembly bowl with canned or leftover fish. Good use of last night's salmon.",
    servings: 1,
    ingredients: [
      { item: "canned tuna or leftover salmon", amount: "1 can or ~4 oz" },
      { item: "cooked quinoa or brown rice", amount: "3/4 cup" },
      { item: "frozen edamame", amount: "1/3 cup", note: "thawed" },
      { item: "cucumber", amount: "1/3", note: "diced" },
      { item: "avocado", amount: "1/2", note: "sliced" },
      { item: "sesame seeds", amount: "1 tsp" },
      { item: "soy sauce", amount: "1 tbsp" },
      { item: "rice vinegar", amount: "1 tsp" },
      { item: "ginger", amount: "1/2 tsp", note: "grated, for dressing" },
    ],
    steps: [
      "Put grain in a bowl or container. Top with fish, edamame, cucumber, avocado.",
      "Mix soy sauce, rice vinegar, and grated ginger. Drizzle on top.",
      "Sprinkle sesame seeds.",
    ],
    categories: ["lunch"],
    prepMinutes: 10,
    batchFriendly: false,
    portable: true,
    onePot: true,
    notes: "If using canned tuna, get the kind in olive oil for better flavor and healthy fats.",
  },

  // ---------------------------------------------------------------------------
  // QUICK / LOW-FRICTION
  // ---------------------------------------------------------------------------
  {
    id: "overnight-oats",
    name: "Overnight Oats",
    description:
      "Zero morning effort. Make 3 jars Sunday, grab one each morning.",
    servings: 1,
    ingredients: [
      { item: "rolled oats", amount: "1/2 cup" },
      { item: "chia seeds", amount: "1 tbsp" },
      { item: "oat milk", amount: "3/4 cup" },
      { item: "maple syrup", amount: "1 tsp" },
      { item: "banana", amount: "1/2", note: "sliced, for topping" },
      { item: "berries", amount: "handful", note: "for topping" },
      { item: "walnuts or almonds", amount: "small handful", note: "for topping" },
    ],
    steps: [
      "Combine oats, chia seeds, oat milk, and maple syrup in a jar or container.",
      "Stir. Put the lid on. Refrigerate overnight (or at least 4 hours).",
      "In the morning, top with banana, berries, and nuts. Eat cold.",
    ],
    categories: ["breakfast"],
    prepMinutes: 5,
    batchFriendly: true,
    portable: true,
    onePot: true,
    notes: "Make 3 at once in mason jars. The base keeps 3-4 days. Add toppings the morning of.",
  },
  {
    id: "bean-grain-scramble",
    name: "Bean and Grain Scramble",
    description:
      "The fridge-cleanout meal. Works with almost any leftover grain and canned bean.",
    servings: 1,
    ingredients: [
      { item: "canned black beans or chickpeas", amount: "1/2 can", note: "drained" },
      { item: "leftover rice or quinoa", amount: "1 cup" },
      { item: "onion", amount: "1/2 small", note: "diced" },
      { item: "ground cumin", amount: "1/2 tsp" },
      { item: "chili flakes", amount: "pinch" },
      { item: "lime", amount: "1/2", note: "juiced" },
      { item: "olive oil", amount: "1 tbsp" },
      { item: "egg", amount: "1", note: "optional, fried on top" },
      { item: "hot sauce", amount: "to taste" },
    ],
    steps: [
      "Heat olive oil in a pan over medium-high heat.",
      "Cook onion 3 minutes. Add beans and grain, spread out flat to get some crispy bits.",
      "Cook without stirring for 2-3 minutes, then stir. Add cumin and chili flakes.",
      "Squeeze lime juice over. Top with a fried egg and hot sauce if you want.",
    ],
    categories: ["flexible"],
    prepMinutes: 10,
    batchFriendly: false,
    portable: true,
    onePot: true,
    notes: "This is the meal for when you have nothing planned but have leftover grain and a can of beans.",
  },
  {
    id: "dal-naan-emergency",
    name: "Dal + Frozen Naan Emergency Meal",
    description:
      "The 'I don't want to think' dinner. Assumes you have leftover dal.",
    servings: 1,
    ingredients: [
      { item: "leftover dal", amount: "1-2 cups" },
      { item: "frozen whole wheat naan", amount: "1-2 pieces" },
      { item: "cucumber", amount: "1/3", note: "sliced" },
      { item: "tomato", amount: "1/2", note: "sliced" },
    ],
    steps: [
      "Reheat dal in a pot or microwave. Add a splash of water if it's thickened.",
      "Toast naan in the oven (400F, 3 minutes) or on a dry skillet.",
      "Slice cucumber and tomato on the side.",
      "Done.",
    ],
    categories: ["dinner"],
    prepMinutes: 5,
    batchFriendly: false,
    portable: false,
    onePot: true,
    notes: "This only works if you always have leftover dal and frozen naan. Keep both stocked.",
  },
  {
    id: "loaded-sweet-potato",
    name: "Loaded Sweet Potato",
    description:
      "Microwave a sweet potato, load it up. Zero cooking skill required.",
    servings: 1,
    ingredients: [
      { item: "sweet potato", amount: "1 large" },
      { item: "canned black beans", amount: "1/2 can", note: "heated" },
      { item: "salsa", amount: "3 tbsp" },
      { item: "avocado", amount: "1/2", note: "sliced or mashed" },
      { item: "lime", amount: "1/2", note: "juiced" },
      { item: "hot sauce", amount: "to taste" },
    ],
    steps: [
      "Poke sweet potato with a fork several times. Microwave 5-7 minutes, flipping halfway, until soft.",
      "Heat black beans in a small pot or microwave.",
      "Split sweet potato open. Load with beans, salsa, avocado.",
      "Squeeze lime, add hot sauce.",
    ],
    categories: ["dinner"],
    prepMinutes: 10,
    batchFriendly: false,
    portable: false,
    onePot: true,
    notes: "Genuinely one of the best effort-to-quality ratios of any meal.",
  },
];
